[webservers]
web ansible_host=13.229.89.63 ansible_user=ubuntu

[private]
ansible ansible_host=10.0.0.135 ansible_user=ubuntu
monitoring ansible_host=10.0.0.136 ansible_user=ubuntu

[private:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -i ~/.ssh/devops-key -W %h:%p ubuntu@13.229.89.63" -o StrictHostKeyChecking=no'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=~/.ssh/devops-key
